# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-25 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoolApp', '0002_auto_20160525_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('delete_time', models.DateField()),
            ],
        ),
    ]
